# Usa a imagem oficial do MySQL como base
FROM mysql:8

# Expondo a porta padrão do MySQL
EXPOSE 3306

# Volume para persistência dos dados
VOLUME ["/var/lib/mysql"]

# Comando padrão (já definido no MySQL oficial, mas incluído aqui por clareza)
CMD ["mysqld"]
